### ISSUE TITLE
Two different REF allele for same position

### ISSUE THREAD

**Issue by jjfarrell** [tobiasrausch/delly#58]
Delly generated the following calls from two different bam files in 2 different runs. The same reference was used for both runs. The issue is the two vcf files actually ended up with 2 different reference alleles for the same position (which should not happen).  Delly version: v0.7.5 is being used.

```
1       724817  DEL00000000     A       <DEL>   0       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.5;CHR2=1;END=224200118;INSLEN=0;HOMLEN=53;PE=3;MAPQ=37;CT=3to5;CIPOS=-53,53;CIEND=-53,53;SR=8;SRQ=0.990476;CONSENSUS=ATGCAATGTAATGGACTCGAATGGAACGGAATGGAATGGACAAGAATTGAATTGAATGGACTGGAATGGAATGGAATGGAATGCAATGGAATGCACTCGAACGGA;CE=1.86058    GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   0/1:-19.0868,0,-13.3173:133:PASS:0:61331624:0:-1:34:3:5:9
1       724817  DEL00000000     T       <DEL>   0       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.5;CHR2=1;END=224200118;INSLEN=0;HOMLEN=53;PE=2;MAPQ=37;CT=3to5;CIPOS=-53,53;CIEND=-53,53;SR=7;SRQ=0.990741;CONSENSUS=CAATGTAATGGACTCGAATGGAACGGAATGGAATGGACAAGAATTGAATTGAATGGACTGGAATGGAATGGAATGGAATGCAATGGAATGCACTCGAACGGATTGGAA;CE=1.85864 GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV   1/1:-18.8828,-2.08997,0:21:PASS:0:79611714:0:-1:52:2:0:7
```

**Comment by tobiasrausch** [comment]
Thanks for reporting this. That's definitely a bug that needs to be fixed - will look into this.

**Comment by tobiasrausch** [comment]
I forgot to update the REF allele after split-read refinement. This is fixed now. Thanks for raising this issue.

**Comment by jjfarrell** [comment]
Does this just bug impact other SV calls besides deletions?

**Comment by tobiasrausch** [comment]
It unfortunately affects all imprecise SVs that have been refined by split-reads. In other words, INFO:PRECISE SVs that use tags as the ALT allele such as <DEL>, <DUP>, <INV> or <TRA>. The small InDels that use exact REF and ALT alleles are fine and also INFO:IMPRECISE SVs are fine. Please note that only the REF allele is wrong in these cases so you might just want to set it to N using:

bcftools view del.bcf | awk 'BEGIN {FS="\t"; OFS="\t";} {if (($1 ~ /^#/) || ($5!="<DEL>")) {print $0;} else {$4="N"; print $0;} }' | bcftools view -O b -o del.fixed.bcf -

Sorry again for the oversight, this should be fixed now in the latest code.

**Comment by jjfarrell** [comment]
I tried the merge again with this the updated delly. This merge  resulted in a slightly different error message at the same position.

 ./merge_vcfs.sh
The REF prefixes differ: T vs A (1,1)
Failed to merge alleles at 1:724817 

This is the line from the vcf file....

1       724817  DEL00000000     T       <DEL>   0       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.5;CHR2=1;END=224200118;INSLEN=0;HOMLEN=53;PE=2;MAPQ=37;CT=3to5;CIPOS=-53,53;CIEND=-53,53;SR=7;SRQ=0.990741;CONSENSUS=CAATGTAATGGACTCGAATGGAACGGAATGGAATGGACAAGAATTGAATTGAATGGACTGGAATGGAATGGAATGGAATGCAATGGAATGCACTCGAACGGATTGGAA;CE=1.85864  GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV    1/1:-18.8828,-2.08997,0:21:PASS:0:79611714:0:-1:52:2:0:7

**Comment by jjfarrell** [comment]
My previous post had a problem with the the vcf line tags. Here it is again with some more details.

The merge program has a problem with the follow line. The line is labeled as precise but has a `<DEL>` as the ALT sequence.  With a PRECISE deletion, the ALT should be a sequence so the first base of the REF and ALT are the same. The END=224200118 is  not close to the POS=724817 and would indicate a extremely large deletion.  So it looks like the bug is not completely fixed yet.

`1       724817  DEL00000000     T       <DEL>   0       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.5;CHR2=1;END=224200118;INSLEN=0;HOMLEN=53;PE=2;MAPQ=37;CT=3to5;CIPOS=-53,53;CI                                                                                END=-53,53;SR=7;SRQ=0.990741;CONSENSUS=CAATGTAATGGACTCGAATGGAACGGAATGGAATGGACAAGAATTGAATTGAATGGACTGGAATGGAATGGAATGGAATGCAATGGAATGCACTCGAACGGATTGGAA;CE=1.85864  GT:GL:GQ:FT:RCL:RC:RCR:CN                                                                                :DR:DV:RR:RV    1/1:-18.8828,-2.08997,0:21:PASS:0:79611714:0:-1:52:2:0:7`
`

**Comment by tobiasrausch** [comment]
Very large deletions can be precise, Delly also tries split-read refinement for those. Delly switches at >500bp from the exact ALT allele to tags <DEL> to save space. Your example is most likely a false positive but from the VCF syntax this looks fine to me. delly call ... should now be fine and update the REF allele correctly for all cases but please let me know if you still see errors.

**Comment by jjfarrell** [comment]
Thanks for the explanation on the Delly PRECISE format.  However, there is still an error message.

When I do the merge with the newer version of Delly, I am  getting this error message:
```
The REF prefixes differ: G vs A (1,1)
Failed to merge alleles at 1:724817 in del/SRR987672.delly.del.vcf.gz
```
So it looks like either the delly merge or delly call program has an bug still.
```
zgrep 724817 del/SRR987672.delly.del.vcf.gz|head
1       724817  DEL00000000     G       <DEL>   0       PASS    PRECISE;SVTYPE=DEL;SVMETHOD=EMBL.DELLYv0.7.5;CHR2=1;END=224200118;PE=2;MAPQ=37;CT=3to5;CIPOS=-53,53;CIEND=-53,53;INSLEN=0;HOMLEN=53;SR=7;SRQ=0.990741;CONSENSUS=CAATGTAATGGACTCGAATGGAACGGAATGGAATGGACAAGAATTGAATTGAATGGACTGGAATGGAATGGAATGGAATGCAATGGAATGCACTCGAACGGATTGGAA;CE=1.85864  GT:GL:GQ:FT:RCL:RC:RCR:CN:DR:DV:RR:RV    1/1:-18.8828,-2.08997,0:21:PASS:0:79611714:0:-1:52:2:0:7
```
```

**Comment by tobiasrausch** [comment]
Thanks for being persistent here. I could reproduce this error now and indeed my previous fix didn't handle all cases properly. I have corrected this now and at least all my test cases are merging fine now. Could you please try again? You need to re-call first with delly call and then delly merge. bcftools merge should also work but doesn't collapse redundant SVs.

**Comment by jjfarrell** [comment]
Thanks Tobias!  The delly merge worked great after re-calling deletions on all the bam files.

**Comment by tobiasrausch** [comment]
Great, thanks for letting me know.

**Comment by Yixiangzhang1996** [comment]
I have the same problem in the conda Delly version，And I am trying to use the lastest Delly version。
The REF prefixes differ: A vs N (1,1)
Failed to merge alleles at scaf_138282:562 in Delly.geno.bcf
